# Generated by Django 3.0 on 2020-01-07 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('last_mod_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='修改时间')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='标签名')),
                ('slug', models.SlugField(blank=True, default='no-slug', max_length=60)),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TradeStrategy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('last_mod_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='修改时间')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='策略名')),
                ('slug', models.SlugField(blank=True, default='no-slug', max_length=60)),
                ('parent_strategy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='traderec.TradeStrategy', verbose_name='父级策略')),
            ],
            options={
                'verbose_name': '交易策略',
                'verbose_name_plural': '交易策略',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TradeRec',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('last_mod_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='修改时间')),
                ('market', models.CharField(blank=True, max_length=50, null=True, verbose_name='市场')),
                ('stock_name', models.CharField(max_length=50, verbose_name='股票名称')),
                ('stock_code', models.CharField(max_length=50, verbose_name='股票代码')),
                ('direction', models.CharField(choices=[('b', '买入'), ('s', '卖出')], default='b', max_length=1, verbose_name='交易类型')),
                ('flag', models.CharField(blank=True, choices=[('s', '建仓'), ('f', '清仓')], default='b', max_length=1, null=True, verbose_name='交易标签')),
                ('price', models.FloatField(verbose_name='交易价格')),
                ('cash', models.FloatField(blank=True, null=True, verbose_name='投入现金额')),
                ('position', models.CharField(max_length=50, verbose_name='仓位')),
                ('pub_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='发布时间')),
                ('status', models.CharField(choices=[('d', '草稿'), ('p', '发表')], default='p', max_length=1, verbose_name='记录状态')),
                ('visible', models.CharField(choices=[('g', '公开'), ('s', '私密'), ('f', '仅好友')], default='s', max_length=1, verbose_name='可见性')),
                ('comment_status', models.CharField(choices=[('o', '打开'), ('c', '关闭')], default='c', max_length=1, verbose_name='评论状态')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='浏览量')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='report_pictures/%Y/%m/%d/', verbose_name='特色图片')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
                ('strategy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='traderec.TradeStrategy', verbose_name='策略')),
            ],
            options={
                'verbose_name': '交易记录',
                'verbose_name_plural': '交易记录',
                'ordering': ['-pub_time'],
                'get_latest_by': 'id',
            },
        ),
    ]
