# Generated by Django 3.0 on 2020-01-11 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traderec', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traderec',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='traderec_pictures/%Y/%m/%d/', verbose_name='特色图片'),
        ),
        migrations.AlterField(
            model_name='traderec',
            name='flag',
            field=models.CharField(blank=True, choices=[('s', '首次建仓'), ('f', '清仓')], default='b', max_length=1, null=True, verbose_name='交易标签'),
        ),
        migrations.AlterField(
            model_name='traderec',
            name='market',
            field=models.CharField(blank=True, choices=[('sh', '上海'), ('sz', '深圳')], max_length=50, null=True, verbose_name='股票市场'),
        ),
        migrations.AlterField(
            model_name='traderec',
            name='status',
            field=models.CharField(choices=[('d', '草稿'), ('p', '发表')], default='p', max_length=1, verbose_name='发布状态'),
        ),
    ]
