# Generated by Django 3.0 on 2020-01-12 10:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('traderec', '0002_auto_20200111_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='traderec',
            name='trade_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='交易时间'),
        ),
        migrations.AlterField(
            model_name='traderec',
            name='flag',
            field=models.CharField(blank=True, choices=[('s', '首次建仓'), ('n', '正常买入/卖出'), ('f', '清仓')], default='b', max_length=1, null=True, verbose_name='交易标签'),
        ),
    ]
