# Generated by Django 3.0 on 2020-01-15 05:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('traderec', '0003_auto_20200112_1839'),
    ]

    operations = [
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('last_mod_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='修改时间')),
                ('market', models.CharField(blank=True, choices=[('sh', '上海'), ('sz', '深圳')], max_length=50, null=True, verbose_name='股票市场')),
                ('stock_name', models.CharField(max_length=50, verbose_name='股票名称')),
                ('stock_code', models.CharField(max_length=50, verbose_name='股票代码')),
                ('price', models.FloatField(verbose_name='持仓价格')),
                ('profit', models.FloatField(verbose_name='利润')),
                ('cash', models.FloatField(blank=True, null=True, verbose_name='投入现金额')),
                ('position', models.CharField(max_length=50, verbose_name='仓位')),
            ],
            options={
                'verbose_name': '持仓',
                'verbose_name_plural': '持仓',
                'ordering': ['-last_mod_time'],
                'get_latest_by': 'id',
            },
        ),
        migrations.CreateModel(
            name='StockNameCodeMap',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('last_mod_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='修改时间')),
                ('market', models.CharField(blank=True, choices=[('sh', '上海'), ('sz', '深圳')], max_length=50, null=True, verbose_name='股票市场')),
                ('stock_name', models.CharField(max_length=50, verbose_name='股票名称')),
                ('stock_code', models.CharField(max_length=50, verbose_name='股票代码')),
                ('is_valid', models.CharField(default='n', max_length=1, verbose_name='是否退市')),
            ],
            options={
                'verbose_name': '股票代码表',
                'verbose_name_plural': '股票代码表',
                'ordering': ['-last_mod_time'],
                'get_latest_by': 'id',
            },
        ),
    ]
