# Generated by Django 3.0 on 2020-01-15 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traderec', '0004_positions_stocknamecodemap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocknamecodemap',
            name='is_valid',
            field=models.CharField(choices=[('y', '退市'), ('n', '可交易')], default='n', max_length=1, verbose_name='是否退市'),
        ),
    ]
