# Generated by Django 3.0 on 2020-01-15 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traderec', '0006_auto_20200115_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='tradestrategy',
            name='slug',
        ),
    ]
