# Generated by Django 3.0 on 2020-01-16 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traderec', '0007_auto_20200115_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='positions',
            name='price',
        ),
        migrations.AddField(
            model_name='positions',
            name='current_price',
            field=models.FloatField(default=0, verbose_name='股票现价'),
        ),
        migrations.AddField(
            model_name='positions',
            name='lots',
            field=models.PositiveIntegerField(default=100, verbose_name='买入量（手）'),
        ),
        migrations.AddField(
            model_name='positions',
            name='position_price',
            field=models.FloatField(default=0, verbose_name='持仓价格'),
        ),
        migrations.AddField(
            model_name='traderec',
            name='is_deleted',
            field=models.CharField(default='n', max_length=1, verbose_name='是否被删除'),
        ),
        migrations.AddField(
            model_name='traderec',
            name='lots',
            field=models.PositiveIntegerField(default=100, verbose_name='买入量（手）'),
        ),
    ]
