# Generated by Django 3.0 on 2020-01-02 13:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chartsnfigures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Placeholder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='栏目名称')),
                ('pl_type', models.CharField(choices=[('t', '首页置顶'), ('l', '首页列表页'), ('s', '首页边栏'), ('r', '人工推荐栏')], default='t', max_length=1, verbose_name='栏位类型')),
                ('sequence', models.IntegerField(unique=True, verbose_name='排序')),
                ('is_enable', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('last_mod_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '首页栏位',
                'verbose_name_plural': '首页栏位',
                'ordering': ['sequence'],
            },
        ),
        migrations.AddField(
            model_name='cnfreport',
            name='to_placeholder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chartsnfigures.Placeholder', verbose_name='栏目位'),
        ),
    ]
