# Generated by Django 3.0 on 2020-01-03 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartsnfigures', '0003_auto_20200103_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='cnfreport',
            name='digest',
            field=models.CharField(max_length=200, null=True, verbose_name='摘要'),
        ),
    ]
