# Generated by Django 3.0 on 2020-01-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartsnfigures', '0004_cnfreport_digest'),
    ]

    operations = [
        migrations.AddField(
            model_name='cnfreport',
            name='slug',
            field=models.SlugField(blank=True, default='no-slug', max_length=200),
        ),
        migrations.AlterField(
            model_name='cnfreport',
            name='digest',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='摘要'),
        ),
    ]
